---
# SPDX-FileCopyrightText: © 2024 Menacit AB <foss@menacit.se>
# SPDX-License-Identifier: CC-BY-SA-4.0
# X-Context: Database course - Ignored files for secrets scanning (slides and labs)
paths-ignore:
  - "resources/labs/**"
